### PR TITLE
added example of an array of arrays

### PR DESCRIPTION
**Pull request by ArtskydJ**
- Fixed syntax highlighting on first example
- Added second example
- Fixed spaces instead of tabs in test
- Added a test for the second example (it passes)

### CODE REVIEW

**Comment by TehShrike** [comment]
Huh, I'm surprised that actually works.  Is `Array.isArray(output)` true?  Is `output.length === 5`?

**Comment by ArtskydJ** [comment]
``` bash
> var ca = require('./')
undefined
> var arr = [ ['a', 'ax', 'app', 'ache', 'anger'], ['b', 'be', 'bin'], ['c', 'ci', 'cat', 'cool', 'chant'] ]
undefined
> var out = ca(arr)
undefined
> typeof out
'object'
> Array.isArray(out)
true
> console.log(out)
[ { '0': 'a', '1': 'b', '2': 'c' },
  { '0': 'ax', '1': 'be', '2': 'ci' },
  { '0': 'app', '1': 'bin', '2': 'cat' },
  { '0': 'ache', '1': undefined, '2': 'cool' },
  { '0': 'anger', '1': undefined, '2': 'chant' } ]
undefined
> out.length
5
> Array.isArray(out[0])
false
>
```

**Comment by TehShrike** [comment]
Huh, crazy!  Well cool then.

**Comment by ArtskydJ** [comment]
I just noticed that there is a discrepancy between `console.log(out)` in the terminal and `console.log(output)` in the readme.

In the terminal, it is `[ {...}, {...} ]`, and in the readme it is `[ [...], [...] ]`.

Fixed in #2.

**Pull request merged**
